name: Holo3D
description: "MNS6 Design, build and testing of a 3D hologram-like RGB LED fan display"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  material_symbols_icons: ^4.2815.1
  web_socket_channel: ^2.4.0
  flutter_colorpicker: ^1.1.0
  sensors_plus: ^7.0.0
  connectivity_plus: ^6.0.0
  network_info_plus: ^5.0.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/Holo3D.png"
  adaptive_icon_background: "#00000000"  # Transparent
  adaptive_icon_foreground: "assets/icons/Holo3D.png"

flutter:
  uses-material-design: true